### ISSUE TITLE
Paragraph numbers are broken in worksheet.md

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/raspberry-pi-zero-time-lapse-cam#6]
Line numbers in Github - Argh!

Adding line spaces around pictures and code blocks results in every line beginning with the number 1.  Removing the line spaces doesn't work well with the text.

One solution is to remove the spaces and add `<p></p>` at the end of the block.  I don't know how else you can do it.

**From this:**

## Deciding on your wearable

First, you need to decide what kind of wearable you would like to make. The Pi Zero is very small and portable so you can wear it in various ways. Here are two examples of wearable time-lapse cameras that you could make with a Raspberry Pi Zero:

1. You could use a lanyard to make a wearable camera that hangs round your neck. Your USB power pack could be stored in a shirt pocket close to the camera. Here is a basic wearable camera setup with a soldered-on LED to alert you when a photograph is being taken, and a button which could be programmed to start and stop photo capture sequences.

  ![Lanyard time-lapse cam](images/james-timelapse.png)

1. You could attach your time-lapse camera to a pair of sunglasses so that it can see what you see. This make uses an additional piece of hardware called a [Blinkt](https://shop.pimoroni.com/products/blinkt), which allows the addition of a cool light pattern whenever a picture is captured. Adding these lights is completely optional. You could skip this part altogether, or you could add lights in a different way, for example by using individual LEDs.

  ![Time-lapse cam as glasses](images/timelapse-specs.png)

**To this:**

## Deciding on your wearable

First, you need to decide what kind of wearable you would like to make. The Pi Zero is very small and portable so you can wear it in various ways. Here are two examples of wearable time-lapse cameras that you could make with a Raspberry Pi Zero:

1. You could use a lanyard to make a wearable camera that hangs round your neck. Your USB power pack could be stored in a shirt pocket close to the camera. Here is a basic wearable camera setup with a soldered-on LED to alert you when a photograph is being taken, and a button which could be programmed to start and stop photo capture sequences.<p></p>
  ![Lanyard time-lapse cam](images/james-timelapse.png)<p></p>
1. You could attach your time-lapse camera to a pair of sunglasses so that it can see what you see. This make uses an additional piece of hardware called a [Blinkt](https://shop.pimoroni.com/products/blinkt), which allows the addition of a cool light pattern whenever a picture is captured. Adding these lights is completely optional. You could skip this part altogether, or you could add lights in a different way, for example by using individual LEDs.<p></p>
  ![Time-lapse cam as glasses](images/timelapse-specs.png)

**By doing this:**

```
## Deciding on your wearable

First, you need to decide what kind of wearable you would like to make. The Pi Zero is very small and portable so you can wear it in various ways. Here are two examples of wearable time-lapse cameras that you could make with a Raspberry Pi Zero:

1. You could use a lanyard to make a wearable camera that hangs round your neck. Your USB power pack could be stored in a shirt pocket close to the camera. Here is a basic wearable camera setup with a soldered-on LED to alert you when a photograph is being taken, and a button which could be programmed to start and stop photo capture sequences.<p></p>
  ![Lanyard time-lapse cam](images/james-timelapse.png)<p></p>
1. You could attach your time-lapse camera to a pair of sunglasses so that it can see what you see. This make uses an additional piece of hardware called a [Blinkt](https://shop.pimoroni.com/products/blinkt), which allows the addition of a cool light pattern whenever a picture is captured. Adding these lights is completely optional. You could skip this part altogether, or you could add lights in a different way, for example by using individual LEDs.<p></p>
  ![Time-lapse cam as glasses](images/timelapse-specs.png)
```

**Comment by lawsie** [comment]
Hi Steve, a bit confused here. If you look on the actual site the line numbers are displaying fine I think? https://www.raspberrypi.org/learning/raspberry-pi-zero-time-lapse-cam/worksheet/

The markdown uses all 1. because if you use 1. for every bullet point it auto inserts the correct numbers without you having to worry about whether you're on bullet point 1, 2, 48 etc. Is that what you mean?

**Comment by SteveAmor** [comment]
Yep, ignore this one.  The web site is fine.  However, if you look at the worksheet in git hub the numbering is incorrect.  Github markdown flavour slightly different.
